name: gestionale_riparazioni
description: Gestionale per riparazioni e magazzino

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  timezone: ^0.9.2
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.6.9
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  decimal: ^2.3.3
  equatable: ^2.0.5

  # UI Packages
  fl_chart: ^0.65.0
  flutter_local_notifications: ^15.1.0+1
  rational: ^2.2.2
  http: ^1.1.0
  timeago: ^3.6.0
  intl: ^0.18.1
  flutter_colorpicker: ^1.0.3 
  table_calendar: ^3.0.9
  path: ^1.8.3
  image_picker: ^1.0.2
  get_it: ^7.6.0
  meta: ^1.9.1
  cloud_firestore_platform_interface: ^6.0.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  uuid: ^3.0.7

  # Utility Packages
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  pdf: ^3.10.7
  excel: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700